/*
 * RFC 2616 Codes Basic Responses
 *
 *
 */
#define	HTTP_CODE_100	"HTTP/1.1 100 Continue\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 10\r\n\r\nContinue\r\n"
#define	HTTP_CODE_101	"HTTP/1.1 101 Switching Protocols\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 21\r\n\r\nSwitching Protocols\r\n"
#define	HTTP_CODE_200	"HTTP/1.1 200 OK\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 4\r\n\r\nOK\r\n"
#define	HTTP_CODE_201	"HTTP/1.1 201 Created\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 9\r\n\r\nCreated\r\n"
#define	HTTP_CODE_202	"HTTP/1.1 202 Accepted\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 10\r\n\r\nAccepted\r\n"
#define	HTTP_CODE_203	"HTTP/1.1 203 Non-Authoritative Information\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 31\r\n\r\nNon-Authoritative Information\r\n"
#define	HTTP_CODE_204	"HTTP/1.1 204 No Content\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 12\r\n\r\nNo Content\r\n"
#define	HTTP_CODE_205	"HTTP/1.1 205 Reset Content\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 15\r\n\r\nReset Content\r\n"
#define	HTTP_CODE_206	"HTTP/1.1 206 Partial Content\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 17\r\n\r\nPartial Content\r\n"
#define	HTTP_CODE_300	"HTTP/1.1 300 Multiple Choices\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 18\r\n\r\nMultiple Choices\r\n"
#define	HTTP_CODE_301	"HTTP/1.1 301 Moved Permanently\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 19\r\n\r\nMoved Permanently\r\n"
#define	HTTP_CODE_302	"HTTP/1.1 302 Found\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 7\r\n\r\nFound\r\n"
#define	HTTP_CODE_303	"HTTP/1.1 303 See Other\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 11\r\n\r\nSee Other\r\n"
#define	HTTP_CODE_304	"HTTP/1.1 304 Not Modified\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 14\r\n\r\nNot Modified\r\n"
#define	HTTP_CODE_305	"HTTP/1.1 305 Use Proxy\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 11\r\n\r\nUse Proxy\r\n"
#define	HTTP_CODE_307	"HTTP/1.1 307 Temporary Redirect\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 20\r\n\r\nTemporary Redirect\r\n"
#define	HTTP_CODE_400	"HTTP/1.1 400 Bad Request\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 13\r\n\r\nBad Request\r\n"
#define	HTTP_CODE_401	"HTTP/1.1 401 Unauthorized\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 14\r\n\r\nUnauthorized\r\n"
#define	HTTP_CODE_402	"HTTP/1.1 402 Payment Required\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 18\r\n\r\nPayment Required\r\n"
#define	HTTP_CODE_403	"HTTP/1.1 403 Forbidden\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 11\r\n\r\nForbidden\r\n"
#define	HTTP_CODE_404	"HTTP/1.1 404 Not Found\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 11\r\n\r\nNot Found\r\n"
#define	HTTP_CODE_405	"HTTP/1.1 405 Method Not Allowed\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 20\r\n\r\nMethod Not Allowed\r\n"
#define	HTTP_CODE_406	"HTTP/1.1 406 Not Acceptable\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 16\r\n\r\nNot Acceptable\r\n"
#define	HTTP_CODE_407	"HTTP/1.1 407 Proxy Authentication Required\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 31\r\n\r\nProxy Authentication Required\r\n"
#define	HTTP_CODE_408	"HTTP/1.1 408 Request Time-out\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 18\r\n\r\nRequest Time-out\r\n"
#define	HTTP_CODE_409	"HTTP/1.1 409 Conflict\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 10\r\n\r\nConflict\r\n"
#define	HTTP_CODE_410	"HTTP/1.1 410 Gone\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 6\r\n\r\nGone\r\n"
#define	HTTP_CODE_411	"HTTP/1.1 411 Length Required\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 17\r\n\r\nLength Required\r\n"
#define	HTTP_CODE_412	"HTTP/1.1 412 Precondition Failed\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 21\r\n\r\nPrecondition Failed\r\n"
#define	HTTP_CODE_413	"HTTP/1.1 413 Request Entity Too Large\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 26\r\n\r\nRequest Entity Too Large\r\n"
#define	HTTP_CODE_414	"HTTP/1.1 414 Request-URI Too Large\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 23\r\n\r\nRequest-URI Too Large\r\n"
#define	HTTP_CODE_415	"HTTP/1.1 415 Unsupported Media Type\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 24\r\n\r\nUnsupported Media Type\r\n"
#define	HTTP_CODE_416	"HTTP/1.1 416 Requested range not satisfiable\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 33\r\n\r\nRequested range not satisfiable\r\n"
#define	HTTP_CODE_417	"HTTP/1.1 417 Expectation Failed\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 20\r\n\r\nExpectation Failed\r\n"
#define	HTTP_CODE_500	"HTTP/1.1 500 Internal Server Error\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 23\r\n\r\nInternal Server Error\r\n"
#define	HTTP_CODE_501	"HTTP/1.1 501 Not Implemented\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 17\r\n\r\nNot Implemented\r\n"
#define	HTTP_CODE_502	"HTTP/1.1 502 Bad Gateway\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 13\r\n\r\nBad Gateway\r\n"
#define	HTTP_CODE_503	"HTTP/1.1 503 Service Unavailable\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 21\r\n\r\nService Unavailable\r\n"
#define	HTTP_CODE_504	"HTTP/1.1 504 Gateway Time-out\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 18\r\n\r\nGateway Time-out\r\n"
#define	HTTP_CODE_505	"HTTP/1.1 505 HTTP Version not supported\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 28\r\n\r\nHTTP Version not supported\r\n"